Add-remove
Gnwin/Todo-list pull request #3
Opened 2022-03-31 22:06 UTC by Gnwin

# Add-Remove

This project is a follow up from the last approved milestone branch list structure.
All requirements for this milestone have been met.

Please check the link to the requirements to begin approval: 
https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md

## Requirements

- Remove all hardcoded items from the tasks array.
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for editing task descriptions.
- By default new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5).
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
- All changes to the To Do List should be saved in local storage.

Please review with the above requirement link.
Thanks as I await your feedback.

2022-03-31 23:08 UTC, brytebee requested changes
Hi, @Gnwin 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- well-documented project✔️
- excellently modularize your code✔️
- add function correctly implemented✔️
- edit function correctly implemented✔️
- excellent management of the state of your objects✔️
- good use of localStoorage to store changes✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +    //   })
- [x] **Required:** Please remove commented code. It is unprofessional to push commented out code. This is against the clean code principle.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +    // parent.children[1].style.background = 'rgb(237 232 177)';
- [x] **Required:** Please remove commented code. It is unprofessional to push commented out code. This is against the clean code principle.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +  // }
- [x] **Required:** Please remove commented code.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +// eslint-disable-next-line import/no-cycle
- [x] **Required:** Kindly fix the linter errors rather than disabling them. This helps you research what to do and also learn more about the JS style guide. Do the same all through your codebase.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +  // eslint-disable-next-line class-methods-use-this
- [x] **Required:** Kindly fix the linter errors rather than disabling them.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +  // eslint-disable-next-line class-methods-use-this
- [x] **Required:** Kindly fix the linter errors rather than disabling them.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +  // eslint-disable-next-line class-methods-use-this
- [x] **Required:** Kindly fix the linter errors rather than disabling them.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +  // eslint-disable-next-line class-methods-use-this
- [x] **Required:** Kindly fix the linter errors rather than disabling them.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/GrabUserInput.js
> +  // eslint-disable-next-line class-methods-use-this
- [x] **Required:** Kindly fix the linter errors rather than disabling them.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/TodoItems.js
> +// eslint-disable-next-line import/no-cycle
- [x] **Required:** Kindly fix the linter errors rather than disabling them.

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/TodoItems.js
> +    if (e.target.checked === true) {
- [ ] **Optional:** This is same as writing 
```
if (e.target.checked) {
  // your conditional code
}
```

2022-03-31 23:08 UTC, brytebee commented on src/assets/js/modules/TodoItems.js
> +  }
- [ ] **Required:** You have done an amazing job. 👏 However, you are required to have a delete function aside from the `clear all completed ` button function. This functions to delete both completed or uncompleted single items and is fired upon clicking the trashcan icon in the video.

![Delete](https://user-images.githubusercontent.com/27709832/161163750-76790a81-94e2-4ba2-a733-7e27491a6126.gif)

2022-04-01 09:40 UTC, mmsesay approved these changes
Hi @Gnwin, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-04 06:14 UTC, merged